import type { Classe, Cor } from "./tipos";

export interface FestaFixa {
  mes: number;
  dia: number;
  nome: string;
  classe: Classe;
  cor: Cor;
  /** Vigílias e oitavas se comportam de modo próprio na precedência. */
  tipo?: "vigilia" | "oitava";
  /** Posto próprio, quando ele foge do que a classe sugere. */
  posto?: number;
  /**
   * Se a festa leva Credo. Não se deduz da classe: depende da categoria.
   * Levam Credo as festas do Senhor, de Nossa Senhora, dos Apóstolos e
   * Evangelistas, dos Doutores da Igreja e a dedicação de igreja.
   */
  credo?: boolean;
}

/**
 * Santoral do Missal de 1962.
 *
 * Estão completas as festas de I e II classe. As de III classe cobrem as mais
 * conhecidas, e as comemorações de IV classe ficaram de fora. Os dados foram
 * escritos a partir do calendário universal e PRECISAM SER CONFERIDOS contra o
 * Divinum Officium antes de uso litúrgico, sobretudo nas de III classe.
 */
export const SANTORAL: FestaFixa[] = [
  // ---------------- janeiro ----------------
  { mes: 1, dia: 5, nome: "Vigília da Epifania", classe: 2, cor: "branco", tipo: "vigilia" },
  { mes: 1, dia: 11, nome: "São Higino", classe: 4, cor: "vermelho" },
  { mes: 1, dia: 13, nome: "Comemoração do Batismo do Senhor", classe: 2, cor: "branco", credo: true },
  { mes: 1, dia: 14, nome: "Santo Hilário", classe: 3, cor: "branco", credo: true },
  { mes: 1, dia: 15, nome: "São Paulo, primeiro eremita", classe: 3, cor: "branco" },
  { mes: 1, dia: 16, nome: "São Marcelo I", classe: 3, cor: "vermelho" },
  { mes: 1, dia: 17, nome: "Santo Antão, abade", classe: 3, cor: "branco" },
  { mes: 1, dia: 18, nome: "Santa Priscila", classe: 4, cor: "vermelho" },
  { mes: 1, dia: 19, nome: "São Mário e companheiros", classe: 4, cor: "vermelho" },
  { mes: 1, dia: 20, nome: "São Fabiano e São Sebastião", classe: 3, cor: "vermelho" },
  { mes: 1, dia: 21, nome: "Santa Inês", classe: 3, cor: "vermelho" },
  { mes: 1, dia: 22, nome: "São Vicente e Santo Anastácio", classe: 3, cor: "vermelho" },
  { mes: 1, dia: 23, nome: "São Raimundo de Peñafort", classe: 3, cor: "branco" },
  { mes: 1, dia: 24, nome: "São Timóteo", classe: 3, cor: "vermelho" },
  { mes: 1, dia: 25, nome: "Conversão de São Paulo", classe: 3, cor: "branco" },
  { mes: 1, dia: 26, nome: "São Policarpo", classe: 3, cor: "vermelho" },
  { mes: 1, dia: 27, nome: "São João Crisóstomo", classe: 3, cor: "branco", credo: true },
  { mes: 1, dia: 28, nome: "São Pedro Nolasco", classe: 3, cor: "branco" },
  { mes: 1, dia: 29, nome: "São Francisco de Sales", classe: 3, cor: "branco", credo: true },
  { mes: 1, dia: 30, nome: "Santa Martina", classe: 3, cor: "vermelho" },
  { mes: 1, dia: 31, nome: "São João Bosco", classe: 3, cor: "branco" },

  // ---------------- fevereiro ----------------
  { mes: 2, dia: 1, nome: "Santo Inácio de Antioquia", classe: 3, cor: "vermelho" },
  { mes: 2, dia: 2, nome: "Purificação de Nossa Senhora", classe: 2, cor: "branco", credo: true },
  { mes: 2, dia: 3, nome: "São Brás", classe: 4, cor: "vermelho" },
  { mes: 2, dia: 4, nome: "Santo André Corsini", classe: 3, cor: "branco" },
  { mes: 2, dia: 5, nome: "Santa Águeda", classe: 3, cor: "vermelho" },
  { mes: 2, dia: 6, nome: "São Tito", classe: 3, cor: "branco" },
  { mes: 2, dia: 7, nome: "São Romualdo", classe: 3, cor: "branco" },
  { mes: 2, dia: 8, nome: "São João de Mata", classe: 3, cor: "branco" },
  { mes: 2, dia: 9, nome: "São Cirilo de Alexandria", classe: 3, cor: "branco", credo: true },
  { mes: 2, dia: 10, nome: "Santa Escolástica", classe: 3, cor: "branco" },
  { mes: 2, dia: 11, nome: "Nossa Senhora de Lourdes", classe: 3, cor: "branco", credo: true },
  { mes: 2, dia: 12, nome: "Sete Santos Fundadores", classe: 3, cor: "branco" },
  { mes: 2, dia: 14, nome: "São Valentim", classe: 4, cor: "vermelho" },
  { mes: 2, dia: 15, nome: "São Faustino e São Jovita", classe: 4, cor: "vermelho" },
  { mes: 2, dia: 18, nome: "São Simeão", classe: 4, cor: "vermelho" },
  { mes: 2, dia: 22, nome: "Cátedra de São Pedro", classe: 2, cor: "branco", credo: true },
  { mes: 2, dia: 23, nome: "São Pedro Damião", classe: 3, cor: "branco", credo: true },
  { mes: 2, dia: 24, nome: "São Matias, apóstolo", classe: 2, cor: "vermelho", credo: true },
  { mes: 2, dia: 27, nome: "São Gabriel de Nossa Senhora das Dores", classe: 3, cor: "branco", credo: true },

  // ---------------- março ----------------
  { mes: 3, dia: 4, nome: "São Casimiro", classe: 3, cor: "branco" },
  { mes: 3, dia: 6, nome: "Santa Perpétua e Santa Felicidade", classe: 3, cor: "vermelho" },
  { mes: 3, dia: 7, nome: "São Tomás de Aquino", classe: 3, cor: "branco", credo: true },
  { mes: 3, dia: 8, nome: "São João de Deus", classe: 3, cor: "branco" },
  { mes: 3, dia: 9, nome: "Santa Francisca Romana", classe: 3, cor: "branco" },
  { mes: 3, dia: 10, nome: "Os Quarenta Mártires", classe: 3, cor: "vermelho" },
  { mes: 3, dia: 12, nome: "São Gregório Magno", classe: 3, cor: "branco", credo: true },
  { mes: 3, dia: 17, nome: "São Patrício", classe: 3, cor: "branco" },
  { mes: 3, dia: 18, nome: "São Cirilo de Jerusalém", classe: 3, cor: "branco", credo: true },
  { mes: 3, dia: 19, nome: "São José, esposo de Nossa Senhora", classe: 1, cor: "branco", credo: true },
  { mes: 3, dia: 21, nome: "São Bento, abade", classe: 3, cor: "branco" },
  { mes: 3, dia: 24, nome: "São Gabriel Arcanjo", classe: 3, cor: "branco" },
  { mes: 3, dia: 25, nome: "Anunciação de Nossa Senhora", classe: 1, cor: "branco", credo: true },
  { mes: 3, dia: 27, nome: "São João Damasceno", classe: 3, cor: "branco", credo: true },
  { mes: 3, dia: 28, nome: "São João Capistrano", classe: 3, cor: "branco" },

  // ---------------- abril ----------------
  { mes: 4, dia: 2, nome: "São Francisco de Paula", classe: 3, cor: "branco" },
  { mes: 4, dia: 4, nome: "Santo Isidoro", classe: 3, cor: "branco", credo: true },
  { mes: 4, dia: 5, nome: "São Vicente Ferrer", classe: 3, cor: "branco" },
  { mes: 4, dia: 11, nome: "São Leão Magno", classe: 3, cor: "branco", credo: true },
  { mes: 4, dia: 13, nome: "São Hermenegildo", classe: 3, cor: "vermelho" },
  { mes: 4, dia: 14, nome: "São Justino", classe: 3, cor: "vermelho" },
  { mes: 4, dia: 17, nome: "Santo Aniceto", classe: 4, cor: "vermelho" },
  { mes: 4, dia: 21, nome: "Santo Anselmo", classe: 3, cor: "branco", credo: true },
  { mes: 4, dia: 22, nome: "São Sotero e São Caio", classe: 3, cor: "vermelho" },
  { mes: 4, dia: 23, nome: "São Jorge", classe: 4, cor: "vermelho" },
  { mes: 4, dia: 24, nome: "São Fidélis de Sigmaringa", classe: 3, cor: "vermelho" },
  { mes: 4, dia: 25, nome: "São Marcos, evangelista", classe: 2, cor: "vermelho", credo: true },
  { mes: 4, dia: 26, nome: "São Cleto e São Marcelino", classe: 3, cor: "vermelho" },
  { mes: 4, dia: 27, nome: "São Pedro Canísio", classe: 3, cor: "branco" },
  { mes: 4, dia: 28, nome: "São Paulo da Cruz", classe: 3, cor: "branco" },
  { mes: 4, dia: 29, nome: "São Pedro de Verona, mártir", classe: 3, cor: "vermelho" },
  { mes: 4, dia: 30, nome: "Santa Catarina de Sena", classe: 3, cor: "branco" },

  // ---------------- maio ----------------
  { mes: 5, dia: 1, nome: "São José Operário", classe: 1, cor: "branco" },
  { mes: 5, dia: 2, nome: "Santo Atanásio", classe: 3, cor: "branco", credo: true },
  { mes: 5, dia: 4, nome: "Santa Mônica", classe: 3, cor: "branco" },
  { mes: 5, dia: 5, nome: "São Pio V", classe: 3, cor: "branco" },
  { mes: 5, dia: 7, nome: "Santo Estanislau", classe: 3, cor: "vermelho" },
  { mes: 5, dia: 9, nome: "São Gregório Nazianzeno", classe: 3, cor: "branco", credo: true },
  { mes: 5, dia: 10, nome: "Santo Antonino", classe: 3, cor: "branco" },
  { mes: 5, dia: 11, nome: "São Filipe e São Tiago, apóstolos", classe: 2, cor: "vermelho", credo: true },
  { mes: 5, dia: 12, nome: "São Nereu, São Aquileu, Santa Domitila e São Pancrácio", classe: 3, cor: "vermelho" },
  { mes: 5, dia: 13, nome: "São Roberto Belarmino", classe: 3, cor: "branco", credo: true },
  { mes: 5, dia: 14, nome: "São Bonifácio", classe: 4, cor: "vermelho" },
  { mes: 5, dia: 15, nome: "São João Batista de La Salle", classe: 3, cor: "branco" },
  { mes: 5, dia: 16, nome: "São Ubaldo", classe: 3, cor: "branco" },
  { mes: 5, dia: 17, nome: "São Pascoal Bailão", classe: 3, cor: "branco" },
  { mes: 5, dia: 18, nome: "São Venâncio", classe: 3, cor: "vermelho" },
  { mes: 5, dia: 19, nome: "São Pedro Celestino", classe: 3, cor: "branco" },
  { mes: 5, dia: 20, nome: "São Bernardino de Sena", classe: 3, cor: "branco" },
  { mes: 5, dia: 25, nome: "São Gregório VII", classe: 3, cor: "branco" },
  { mes: 5, dia: 26, nome: "São Filipe Néri", classe: 3, cor: "branco" },
  { mes: 5, dia: 27, nome: "São Beda, o Venerável", classe: 3, cor: "branco", credo: true },
  { mes: 5, dia: 28, nome: "Santo Agostinho de Cantuária", classe: 3, cor: "branco" },
  { mes: 5, dia: 29, nome: "Santa Maria Madalena de Pazzi", classe: 3, cor: "branco" },
  { mes: 5, dia: 30, nome: "São Félix I", classe: 4, cor: "vermelho" },
  { mes: 5, dia: 31, nome: "Nossa Senhora Rainha", classe: 2, cor: "branco", credo: true },

  // ---------------- junho ----------------
  { mes: 6, dia: 1, nome: "Santa Ângela Merici", classe: 3, cor: "branco" },
  { mes: 6, dia: 2, nome: "São Marcelino, São Pedro e Santo Erasmo", classe: 4, cor: "vermelho" },
  { mes: 6, dia: 4, nome: "São Francisco Caracciolo", classe: 3, cor: "branco" },
  { mes: 6, dia: 5, nome: "São Bonifácio, bispo e mártir", classe: 3, cor: "vermelho" },
  { mes: 6, dia: 6, nome: "São Norberto", classe: 3, cor: "branco" },
  { mes: 6, dia: 9, nome: "São Primo e São Feliciano", classe: 4, cor: "vermelho" },
  { mes: 6, dia: 10, nome: "Santa Margarida da Escócia", classe: 3, cor: "branco" },
  { mes: 6, dia: 11, nome: "São Barnabé, apóstolo", classe: 3, cor: "vermelho", credo: true },
  { mes: 6, dia: 12, nome: "São João de São Facundo", classe: 3, cor: "branco" },
  { mes: 6, dia: 13, nome: "Santo Antônio de Pádua", classe: 3, cor: "branco" },
  { mes: 6, dia: 14, nome: "São Basílio Magno", classe: 3, cor: "branco", credo: true },
  { mes: 6, dia: 15, nome: "São Vito, São Modesto e Santa Crescência", classe: 4, cor: "vermelho" },
  { mes: 6, dia: 17, nome: "São Gregório Barbarigo", classe: 3, cor: "branco" },
  { mes: 6, dia: 18, nome: "Santo Efrém", classe: 3, cor: "branco", credo: true },
  { mes: 6, dia: 19, nome: "Santa Juliana de Falconieri", classe: 3, cor: "branco" },
  { mes: 6, dia: 20, nome: "São Silvério", classe: 4, cor: "vermelho" },
  { mes: 6, dia: 21, nome: "São Luís Gonzaga", classe: 3, cor: "branco" },
  { mes: 6, dia: 22, nome: "São Paulino de Nola", classe: 3, cor: "branco" },
  { mes: 6, dia: 23, nome: "Vigília de São João Batista", classe: 2, cor: "roxo", tipo: "vigilia" },
  { mes: 6, dia: 24, nome: "Natividade de São João Batista", classe: 1, cor: "branco" },
  { mes: 6, dia: 25, nome: "São Guilherme", classe: 3, cor: "branco" },
  { mes: 6, dia: 26, nome: "São João e São Paulo", classe: 3, cor: "vermelho" },
  { mes: 6, dia: 28, nome: "Vigília de São Pedro e São Paulo", classe: 2, cor: "roxo", tipo: "vigilia" },
  { mes: 6, dia: 29, nome: "São Pedro e São Paulo, apóstolos", classe: 1, cor: "vermelho", credo: true },
  { mes: 6, dia: 30, nome: "Comemoração de São Paulo", classe: 3, cor: "vermelho" },

  // ---------------- julho ----------------
  { mes: 7, dia: 1, nome: "Preciosíssimo Sangue de Nosso Senhor", classe: 1, cor: "vermelho", credo: true },
  { mes: 7, dia: 2, nome: "Visitação de Nossa Senhora", classe: 2, cor: "branco", credo: true },
  { mes: 7, dia: 3, nome: "São Leão II", classe: 3, cor: "branco" },
  { mes: 7, dia: 5, nome: "Santo Antônio Maria Zacarias", classe: 3, cor: "branco" },
  { mes: 7, dia: 7, nome: "São Cirilo e São Metódio", classe: 3, cor: "branco" },
  { mes: 7, dia: 8, nome: "Santa Isabel de Portugal", classe: 3, cor: "branco" },
  { mes: 7, dia: 10, nome: "Os Sete Santos Irmãos", classe: 3, cor: "vermelho" },
  { mes: 7, dia: 11, nome: "São Pio I", classe: 4, cor: "vermelho" },
  { mes: 7, dia: 12, nome: "São João Gualberto", classe: 3, cor: "branco" },
  { mes: 7, dia: 14, nome: "São Boaventura", classe: 3, cor: "branco", credo: true },
  { mes: 7, dia: 15, nome: "São Henrique", classe: 3, cor: "branco" },
  { mes: 7, dia: 16, nome: "Nossa Senhora do Carmo", classe: 3, cor: "branco", credo: true },
  { mes: 7, dia: 17, nome: "Santo Aleixo", classe: 3, cor: "branco" },
  { mes: 7, dia: 18, nome: "São Camilo de Léllis", classe: 3, cor: "branco" },
  { mes: 7, dia: 19, nome: "São Vicente de Paulo", classe: 3, cor: "branco" },
  { mes: 7, dia: 20, nome: "São Jerônimo Emiliani", classe: 3, cor: "branco", credo: true },
  { mes: 7, dia: 21, nome: "Santa Praxedes", classe: 4, cor: "branco" },
  { mes: 7, dia: 22, nome: "Santa Maria Madalena", classe: 3, cor: "branco" },
  { mes: 7, dia: 23, nome: "São Apolinário", classe: 3, cor: "vermelho" },
  { mes: 7, dia: 24, nome: "Vigília de São Tiago", classe: 3, cor: "roxo", tipo: "vigilia" },
  { mes: 7, dia: 25, nome: "São Tiago, apóstolo", classe: 2, cor: "vermelho", credo: true },
  { mes: 7, dia: 26, nome: "Santa Ana, mãe de Nossa Senhora", classe: 2, cor: "branco", credo: true },
  { mes: 7, dia: 27, nome: "São Pantaleão", classe: 4, cor: "vermelho" },
  { mes: 7, dia: 28, nome: "São Nazário, São Celso, São Vítor e Santo Inocêncio", classe: 3, cor: "vermelho" },
  { mes: 7, dia: 29, nome: "Santa Marta", classe: 3, cor: "branco" },
  { mes: 7, dia: 30, nome: "São Abdon e São Senén", classe: 4, cor: "vermelho" },
  { mes: 7, dia: 31, nome: "Santo Inácio de Loyola", classe: 3, cor: "branco" },

  // ---------------- agosto ----------------
  { mes: 8, dia: 1, nome: "Os Santos Macabeus", classe: 4, cor: "vermelho" },
  { mes: 8, dia: 2, nome: "Santo Afonso Maria de Ligório", classe: 3, cor: "branco", credo: true },
  { mes: 8, dia: 4, nome: "São Domingos", classe: 3, cor: "branco" },
  { mes: 8, dia: 5, nome: "Nossa Senhora das Neves", classe: 3, cor: "branco", credo: true },
  { mes: 8, dia: 6, nome: "Transfiguração do Senhor", classe: 2, cor: "branco", credo: true },
  { mes: 8, dia: 7, nome: "São Caetano", classe: 3, cor: "branco" },
  { mes: 8, dia: 8, nome: "São João Maria Vianney", classe: 3, cor: "branco" },
  { mes: 8, dia: 9, nome: "Vigília de São Lourenço", classe: 3, cor: "roxo", tipo: "vigilia" },
  { mes: 8, dia: 10, nome: "São Lourenço, mártir", classe: 2, cor: "vermelho" },
  { mes: 8, dia: 11, nome: "São Tibúrcio e Santa Susana", classe: 4, cor: "vermelho" },
  { mes: 8, dia: 12, nome: "Santa Clara", classe: 3, cor: "branco" },
  { mes: 8, dia: 13, nome: "Santo Hipólito e São Cassiano", classe: 4, cor: "vermelho" },
  { mes: 8, dia: 14, nome: "Vigília da Assunção", classe: 2, cor: "roxo", tipo: "vigilia" },
  { mes: 8, dia: 15, nome: "Assunção de Nossa Senhora", classe: 1, cor: "branco", credo: true },
  { mes: 8, dia: 16, nome: "São Joaquim, pai de Nossa Senhora", classe: 2, cor: "branco", credo: true },
  { mes: 8, dia: 17, nome: "São Jacinto", classe: 3, cor: "branco" },
  { mes: 8, dia: 18, nome: "Santo Agapito", classe: 4, cor: "vermelho" },
  { mes: 8, dia: 19, nome: "São João Eudes", classe: 3, cor: "branco" },
  { mes: 8, dia: 20, nome: "São Bernardo", classe: 3, cor: "branco" },
  { mes: 8, dia: 21, nome: "Santa Joana Francisca de Chantal", classe: 3, cor: "branco" },
  { mes: 8, dia: 22, nome: "Imaculado Coração de Maria", classe: 2, cor: "branco", credo: true },
  { mes: 8, dia: 23, nome: "São Filipe Benício", classe: 3, cor: "branco" },
  { mes: 8, dia: 24, nome: "São Bartolomeu, apóstolo", classe: 2, cor: "vermelho", credo: true },
  { mes: 8, dia: 25, nome: "São Luís, rei de França", classe: 3, cor: "branco" },
  { mes: 8, dia: 26, nome: "São Zeferino", classe: 4, cor: "vermelho" },
  { mes: 8, dia: 27, nome: "São José de Calasanz", classe: 3, cor: "branco" },
  { mes: 8, dia: 28, nome: "Santo Agostinho", classe: 3, cor: "branco", credo: true },
  { mes: 8, dia: 29, nome: "Degolação de São João Batista", classe: 3, cor: "vermelho" },
  { mes: 8, dia: 30, nome: "Santa Rosa de Lima", classe: 3, cor: "branco" },
  { mes: 8, dia: 31, nome: "São Raimundo Nonato", classe: 3, cor: "branco" },

  // ---------------- setembro ----------------
  { mes: 9, dia: 1, nome: "Santo Egídio", classe: 4, cor: "branco" },
  { mes: 9, dia: 2, nome: "Santo Estêvão da Hungria", classe: 3, cor: "branco" },
  { mes: 9, dia: 3, nome: "São Pio X", classe: 3, cor: "branco" },
  { mes: 9, dia: 5, nome: "São Lourenço Justiniano", classe: 3, cor: "branco" },
  { mes: 9, dia: 8, nome: "Natividade de Nossa Senhora", classe: 2, cor: "branco", credo: true },
  { mes: 9, dia: 9, nome: "São Gorgônio", classe: 4, cor: "vermelho" },
  { mes: 9, dia: 10, nome: "São Nicolau de Tolentino", classe: 3, cor: "branco" },
  { mes: 9, dia: 11, nome: "São Proto e São Jacinto", classe: 4, cor: "vermelho" },
  { mes: 9, dia: 12, nome: "Santíssimo Nome de Maria", classe: 3, cor: "branco" },
  { mes: 9, dia: 14, nome: "Exaltação da Santa Cruz", classe: 2, cor: "vermelho", credo: true },
  { mes: 9, dia: 15, nome: "Sete Dores de Nossa Senhora", classe: 2, cor: "branco", credo: true },
  { mes: 9, dia: 16, nome: "São Cornélio e São Cipriano", classe: 3, cor: "vermelho" },
  { mes: 9, dia: 17, nome: "Estigmas de São Francisco", classe: 3, cor: "branco" },
  { mes: 9, dia: 18, nome: "São José de Cupertino", classe: 3, cor: "branco" },
  { mes: 9, dia: 19, nome: "São Januário e companheiros", classe: 3, cor: "vermelho" },
  { mes: 9, dia: 20, nome: "Santo Eustáquio e companheiros", classe: 4, cor: "vermelho" },
  { mes: 9, dia: 21, nome: "São Mateus, apóstolo e evangelista", classe: 2, cor: "vermelho", credo: true },
  { mes: 9, dia: 22, nome: "São Tomás de Vilanova", classe: 3, cor: "branco" },
  { mes: 9, dia: 23, nome: "São Lino", classe: 4, cor: "vermelho" },
  { mes: 9, dia: 24, nome: "Nossa Senhora das Mercês", classe: 3, cor: "branco", credo: true },
  { mes: 9, dia: 26, nome: "São Cipriano e Santa Justina", classe: 4, cor: "vermelho" },
  { mes: 9, dia: 27, nome: "São Cosme e São Damião", classe: 3, cor: "vermelho" },
  { mes: 9, dia: 28, nome: "São Venceslau", classe: 3, cor: "vermelho" },
  { mes: 9, dia: 29, nome: "Dedicação de São Miguel Arcanjo", classe: 1, cor: "branco", credo: true },
  { mes: 9, dia: 30, nome: "São Jerônimo", classe: 3, cor: "branco", credo: true },

  // ---------------- outubro ----------------
  { mes: 10, dia: 1, nome: "São Remígio", classe: 4, cor: "branco" },
  { mes: 10, dia: 2, nome: "Santos Anjos da Guarda", classe: 3, cor: "branco" },
  { mes: 10, dia: 3, nome: "Santa Teresinha do Menino Jesus", classe: 3, cor: "branco" },
  { mes: 10, dia: 4, nome: "São Francisco de Assis", classe: 3, cor: "branco" },
  { mes: 10, dia: 5, nome: "São Plácido e companheiros", classe: 4, cor: "vermelho" },
  { mes: 10, dia: 6, nome: "São Bruno", classe: 3, cor: "branco" },
  { mes: 10, dia: 7, nome: "Nossa Senhora do Rosário", classe: 2, cor: "branco", credo: true },
  { mes: 10, dia: 8, nome: "Santa Brígida", classe: 3, cor: "branco" },
  { mes: 10, dia: 9, nome: "São João Leonardi", classe: 3, cor: "branco" },
  { mes: 10, dia: 10, nome: "São Francisco de Bórgia", classe: 3, cor: "branco" },
  { mes: 10, dia: 11, nome: "Maternidade de Nossa Senhora", classe: 2, cor: "branco", credo: true },
  { mes: 10, dia: 13, nome: "São Eduardo", classe: 3, cor: "branco" },
  { mes: 10, dia: 14, nome: "São Calisto I", classe: 3, cor: "vermelho" },
  { mes: 10, dia: 15, nome: "Santa Teresa de Ávila", classe: 3, cor: "branco", credo: true },
  { mes: 10, dia: 16, nome: "Santa Edwiges", classe: 3, cor: "branco" },
  { mes: 10, dia: 17, nome: "Santa Margarida Maria Alacoque", classe: 3, cor: "branco" },
  { mes: 10, dia: 18, nome: "São Lucas, evangelista", classe: 2, cor: "vermelho", credo: true },
  { mes: 10, dia: 19, nome: "São Pedro de Alcântara", classe: 3, cor: "branco" },
  { mes: 10, dia: 20, nome: "São João Cântio", classe: 3, cor: "branco" },
  { mes: 10, dia: 21, nome: "Santo Hilarião", classe: 4, cor: "branco" },
  { mes: 10, dia: 23, nome: "Santo Antônio Maria Claret", classe: 3, cor: "branco" },
  { mes: 10, dia: 24, nome: "São Rafael Arcanjo", classe: 3, cor: "branco" },
  { mes: 10, dia: 25, nome: "São Crisanto e Santa Daria", classe: 4, cor: "vermelho" },
  { mes: 10, dia: 26, nome: "São Evaristo", classe: 4, cor: "vermelho" },
  { mes: 10, dia: 28, nome: "São Simão e São Judas, apóstolos", classe: 2, cor: "vermelho", credo: true },

  // ---------------- novembro ----------------
  { mes: 11, dia: 1, nome: "Todos os Santos", classe: 1, cor: "branco" },
  { mes: 11, dia: 2, nome: "Comemoração de Todos os Fiéis Defuntos", classe: 1, cor: "preto", posto: 10 },
  { mes: 11, dia: 4, nome: "São Carlos Borromeu", classe: 3, cor: "branco" },
  { mes: 11, dia: 8, nome: "Os Quatro Santos Coroados", classe: 4, cor: "vermelho" },
  { mes: 11, dia: 9, nome: "Dedicação da Arquibasílica do Salvador", classe: 2, cor: "branco", credo: true },
  { mes: 11, dia: 10, nome: "Santo André Avelino", classe: 3, cor: "branco" },
  { mes: 11, dia: 11, nome: "São Martinho de Tours", classe: 3, cor: "branco" },
  { mes: 11, dia: 12, nome: "São Martinho I", classe: 3, cor: "vermelho" },
  { mes: 11, dia: 13, nome: "São Diego", classe: 3, cor: "branco" },
  { mes: 11, dia: 14, nome: "São Josafá", classe: 3, cor: "vermelho" },
  { mes: 11, dia: 15, nome: "Santo Alberto Magno", classe: 3, cor: "branco", credo: true },
  { mes: 11, dia: 16, nome: "Santa Gertrudes", classe: 3, cor: "branco" },
  { mes: 11, dia: 17, nome: "São Gregório Taumaturgo", classe: 3, cor: "branco" },
  { mes: 11, dia: 18, nome: "Dedicação das Basílicas de São Pedro e São Paulo", classe: 3, cor: "branco", credo: true },
  { mes: 11, dia: 19, nome: "Santa Isabel da Hungria", classe: 3, cor: "branco" },
  { mes: 11, dia: 20, nome: "São Félix de Valois", classe: 3, cor: "branco" },
  { mes: 11, dia: 21, nome: "Apresentação de Nossa Senhora", classe: 3, cor: "branco", credo: true },
  { mes: 11, dia: 22, nome: "Santa Cecília", classe: 3, cor: "vermelho" },
  { mes: 11, dia: 23, nome: "São Clemente I", classe: 3, cor: "vermelho" },
  { mes: 11, dia: 24, nome: "São João da Cruz", classe: 3, cor: "branco", credo: true },
  { mes: 11, dia: 25, nome: "Santa Catarina de Alexandria", classe: 3, cor: "vermelho" },
  { mes: 11, dia: 26, nome: "São Silvestre, abade", classe: 3, cor: "branco" },
  { mes: 11, dia: 29, nome: "Vigília de Santo André", classe: 3, cor: "roxo", tipo: "vigilia" },
  { mes: 11, dia: 30, nome: "Santo André, apóstolo", classe: 2, cor: "vermelho", credo: true },

  // ---------------- dezembro ----------------
  { mes: 12, dia: 2, nome: "Santa Bibiana", classe: 3, cor: "vermelho" },
  { mes: 12, dia: 3, nome: "São Francisco Xavier", classe: 3, cor: "branco" },
  { mes: 12, dia: 4, nome: "São Pedro Crisólogo", classe: 3, cor: "branco", credo: true },
  { mes: 12, dia: 5, nome: "São Sabas", classe: 4, cor: "branco" },
  { mes: 12, dia: 6, nome: "São Nicolau", classe: 3, cor: "branco" },
  { mes: 12, dia: 7, nome: "Santo Ambrósio", classe: 3, cor: "branco", credo: true },
  { mes: 12, dia: 8, nome: "Imaculada Conceição de Nossa Senhora", classe: 1, cor: "branco", credo: true },
  { mes: 12, dia: 10, nome: "São Melquíades", classe: 4, cor: "vermelho" },
  { mes: 12, dia: 11, nome: "São Dâmaso I", classe: 3, cor: "branco" },
  { mes: 12, dia: 13, nome: "Santa Luzia", classe: 3, cor: "vermelho" },
  { mes: 12, dia: 16, nome: "São Eusébio", classe: 3, cor: "vermelho" },
  { mes: 12, dia: 21, nome: "São Tomé, apóstolo", classe: 2, cor: "vermelho", credo: true },
  { mes: 12, dia: 24, nome: "Vigília do Natal", classe: 1, cor: "roxo", tipo: "vigilia" },
  { mes: 12, dia: 26, nome: "Santo Estêvão, primeiro mártir", classe: 2, cor: "vermelho" },
  { mes: 12, dia: 27, nome: "São João, apóstolo e evangelista", classe: 2, cor: "branco", credo: true },
  { mes: 12, dia: 28, nome: "Santos Inocentes", classe: 2, cor: "vermelho" },
  { mes: 12, dia: 29, nome: "São Tomás Becket", classe: 3, cor: "vermelho" },
  { mes: 12, dia: 31, nome: "São Silvestre I", classe: 3, cor: "branco" },
];

/** Festas fixas de uma data. */
export function festasDe(mes: number, dia: number): FestaFixa[] {
  return SANTORAL.filter((f) => f.mes === mes && f.dia === dia);
}
